{
    "MixDataAll": [
        {
            "id": "4",
            "ImageUrlHorizontal": "https://apsolution.org/Poster/h1/Warning%20%282021%29.jpg",
            "ImageUrlVertical": "https://apsolution.org/Poster/v1/Warning%20%282021%29.jpg",
            "movieName": "Warning (2021)",
            "htmlFile": "https://www.15558",
            "directOne": "Hindi",
            "imbd": "8.0",
            "rating": "pDVDRip",
            "catergory": "Action",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "yes",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "21",
            "ImageUrlHorizontal": "https://apsolution.org/Poster/h1/Puaada%20%282021%29.jpg",
            "ImageUrlVertical": "https://apsolution.org/Poster/v1/Puaada%20%282021%29.jpg",
            "movieName": "Puaada (2021)",
            "htmlFile": "https://www.15405",
            "directOne": "Punjabi",
            "imbd": "7.0",
            "rating": "HD 720p",
            "catergory": "Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "yes",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "38",
            "ImageUrlHorizontal": "https://apsolution.org/Poster/h1/Moosa%20Jatt%20%282021%29.jpg",
            "ImageUrlVertical": "https://apsolution.org/Poster/v1/Moosa%20Jatt%20%282021%29.jpg",
            "movieName": "Moosa Jatt (2021)",
            "htmlFile": "https://www.15331",
            "directOne": "Punjabi",
            "imbd": "6.7",
            "rating": "HD 720p",
            "catergory": "Action",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "yes",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "40",
            "ImageUrlHorizontal": "https://apsolution.org/Poster/h1/Yes%20I%20Am%20Student%20%282021%29.jpg",
            "ImageUrlVertical": "https://apsolution.org/Poster/v1/Yes%20I%20Am%20Student%20%282021%29.jpg",
            "movieName": "Yes I Am Student (2021)",
            "htmlFile": "https://www.15333",
            "directOne": "Punjabi",
            "imbd": "6.7",
            "rating": "pDVDRip",
            "catergory": "Drama",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "yes",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "44",
            "ImageUrlHorizontal": "https://apsolution.org/Poster/h1/Honsla%20Rakh%20%282021%29.jpg",
            "ImageUrlVertical": "https://apsolution.org/Poster/v1/Honsla%20Rakh%20%282021%29.jpg",
            "movieName": "Honsla Rakh (2021)",
            "htmlFile": "https://www.15315",
            "directOne": "Punjabi",
            "imbd": "9.4",
            "rating": "HD 720p",
            "catergory": "Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "yes",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "56",
            "ImageUrlHorizontal": "https://apsolution.org/Poster/h1/Jinne%20Jamme%20Saare%20Nikamme%20%282021%29.jpg",
            "ImageUrlVertical": "https://apsolution.org/Poster/v1/Jinne%20Jamme%20Saare%20Nikamme%20%282021%29.jpg",
            "movieName": "Jinne Jamme Saare Nikamme (2021)",
            "htmlFile": "https://www.15162",
            "directOne": "Punjabi",
            "imbd": "7.8",
            "rating": "HD 720p",
            "catergory": "Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "yes",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "63",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/efaa/babapmamthxsqzt6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/76d1/xos3o4ah7z9pgm66g.jpg",
            "movieName": "Chal Mera Putt 2 (2020)",
            "htmlFile": "https://www.13075",
            "directOne": "Punjabi",
            "imbd": "8.0",
            "rating": "HD 720p",
            "catergory": "Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "Chal Mera Putt",
            "pathName": "2"
        },
        {
            "id": "64",
            "ImageUrlHorizontal": "https://apsolution.org/Poster/h1/Chal%20Mera%20Putt%203%20%282021%29.jpg",
            "ImageUrlVertical": "https://apsolution.org/Poster/v1/Chal%20Mera%20Putt%203%20%282021%29.jpg",
            "movieName": "Chal Mera Putt 3 (2021)",
            "htmlFile": "https://www.15039",
            "directOne": "Punjabi",
            "imbd": "8.0",
            "rating": "pDVDRip",
            "catergory": "Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "Chal Mera Putt",
            "pathName": "3"
        },
        {
            "id": "82",
            "ImageUrlHorizontal": "https://apsolution.org/Poster/h1/Yaara%20Ve%20%282019%29.jpg",
            "ImageUrlVertical": "https://apsolution.org/Poster/v1/Yaara%20Ve%20%282019%29.jpg",
            "movieName": "Yaara Ve (2019)",
            "htmlFile": "https://www.15152",
            "directOne": "Punjabi",
            "imbd": "6.8",
            "rating": "HD 720p",
            "catergory": "Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "yes",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "85",
            "ImageUrlHorizontal": "https://apsolution.org/Poster/h1/Qismat%202%20%282021%29.jpg",
            "ImageUrlVertical": "https://apsolution.org/Poster/v1/Qismat%202%20%282021%29.jpg",
            "movieName": "Qismat 2 (2021)",
            "htmlFile": "https://www.15048",
            "directOne": "Punjabi",
            "imbd": "6.6",
            "rating": "HD 720p",
            "catergory": "Drama",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "yes",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "107",
            "ImageUrlHorizontal": "https://apsolution.org/Poster/h/Jinde%20Meriye%20%282020%29.jpg",
            "ImageUrlVertical": "https://apsolution.org/Poster/v/Jinde%20Meriye%20%282020%29.jpg",
            "movieName": "Jinde Meriye (2020)",
            "htmlFile": "https://www.14180",
            "directOne": "Punjabi",
            "imbd": "7.7",
            "rating": "HD 720p",
            "catergory": "Action",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "148",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/fd4c/84my367ps98ab2p6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/1277/yej992n3q7iel0z6g.jpg",
            "movieName": "Kuriyan Jawan Bapu Preshan (2021)",
            "htmlFile": "https://www.13838",
            "directOne": "Punjabi",
            "imbd": "6.4",
            "rating": "HD 720p",
            "catergory": "Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "224",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/5722/iobiv0mya9omrku6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/c0b7/6fzv0xr4iz3gg106g.jpg",
            "movieName": "Vadda Kalakaar (2018)",
            "htmlFile": "https://www.13208",
            "directOne": "Punjabi",
            "imbd": "5.4",
            "rating": "HD 720p",
            "catergory": "Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "231",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/f239/77r2pzz3d8mu4oh6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/24b5/hp5opi68zir0f0a6g.jpg",
            "movieName": "Khatre Da Ghuggu (2021)",
            "htmlFile": "https://www.13145",
            "directOne": "Punjabi",
            "imbd": "6.6",
            "rating": "HD 720p",
            "catergory": "Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "416",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/5c41/58trno4bnrnt00w6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/abd1/1uw14rqklzfno4k6g.jpg",
            "movieName": "Jagga Jogaran Joga (2019)",
            "htmlFile": "https://www.1789",
            "directOne": "Punjabi",
            "imbd": "6.2",
            "rating": "HD 720p",
            "catergory": "Drama",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "614",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/9d34/ik99fgsecksamoe6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/403a/84jb8gclpc036ip6g.jpg",
            "movieName": "Sufna (2020)",
            "htmlFile": "https://www.2916",
            "directOne": "Punjabi",
            "imbd": "8.2",
            "rating": "HD 720p",
            "catergory": "Drama",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "623",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/bb8b/2gzhbd48h5oygm06g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/b7f6/bs8q77rb0g3n44k6g.jpg",
            "movieName": "Zakhmi (2020)",
            "htmlFile": "https://www.2838",
            "directOne": "Punjabi",
            "imbd": "5.8",
            "rating": "HD 720p",
            "catergory": "Action",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "631",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/476b/khyfa2h3xglwkg06g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/7da5/s9h2994iy154lp96g.jpg",
            "movieName": "Sikander 2 (2019)",
            "htmlFile": "https://www.2806",
            "directOne": "Punjabi",
            "imbd": "8.3",
            "rating": "HD 720p",
            "catergory": "Drama",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "637",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/d2a2/hfzi3dbj8jql7ac6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/d55e/gxlmruza9ccevtb6g.jpg",
            "movieName": "Jhalle (2019)",
            "htmlFile": "https://www.2779",
            "directOne": "Punjabi",
            "imbd": "5.8",
            "rating": "HD 720p",
            "catergory": "Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "699",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/2c00/otndukupen1rurd6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/b984/evkre9u6lj6nxoc6g.jpg",
            "movieName": "Jora The Second Chapter (2020)",
            "htmlFile": "https://www.2603",
            "directOne": "Punjabi",
            "imbd": "8.3",
            "rating": "pDVDRip",
            "catergory": "Action",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "725",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/68fd/gv7sicy0w1eshdb6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/b412/tx7cvoyqr3rinku6g.jpg",
            "movieName": "Ek Sandhu Honda Si (2020)",
            "htmlFile": "https://www.2516",
            "directOne": "Punjabi",
            "imbd": "4.9",
            "rating": "HD 720p",
            "catergory": "Action",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "740",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/fb40/m1n01nvwj7xwijf6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/5753/aetpy5cyahtjsm46g.jpg",
            "movieName": "Ishqaa (2019)",
            "htmlFile": "https://www.2390",
            "directOne": "Punjabi",
            "imbd": "3.2",
            "rating": "HD 720p",
            "catergory": "Drama",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "813",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/1fbc/39xl2rlhv5scoua6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/7de9/v2z9kiydfpq0g8p6g.jpg",
            "movieName": "Gidarh Singhi (2019)",
            "htmlFile": "https://www.9527",
            "directOne": "Punjabi",
            "imbd": "5.6",
            "rating": "HD 720p",
            "catergory": "Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "827",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/f2b8/0vrfdmgf2b4ihxr6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/52c8/utzyjtcf2ltz1j96g.jpg",
            "movieName": "Doorbeen (2019)",
            "htmlFile": "https://www.9476",
            "directOne": "Punjabi",
            "imbd": "5.9",
            "rating": "HD 720p",
            "catergory": "Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "840",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/803d/io3t2m6zduhvv4h6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/3d55/2idfxi4qasdmdcj6g.jpg",
            "movieName": "Jind Jaan (2019)",
            "htmlFile": "https://www.9458",
            "directOne": "Punjabi",
            "imbd": "2.4",
            "rating": "HD 720p",
            "catergory": "Drama",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "894",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/9d7f/jwh7jvjhtndddpm6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/e5ec/5gojlb5s46zn9ip6g.jpg",
            "movieName": "Nikka Zaildar 3 (2019)",
            "htmlFile": "https://www.8977",
            "directOne": "Punjabi",
            "imbd": "3.9",
            "rating": "HD 720p",
            "catergory": "Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "yes",
            "keyName": "Nikka Zaildar",
            "pathName": "3"
        },
        {
            "id": "900",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/c3fb/uztnedb5a4cs8e96g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/a6b3/u5zq0cdnbwopmf26g.jpg",
            "movieName": "Chal Mera Putt (2019)",
            "htmlFile": "https://www.8948",
            "directOne": "Punjabi",
            "imbd": "7.3",
            "rating": "HD 720p",
            "catergory": "Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "yes",
            "keyName": "Chal Mera Putt",
            "pathName": "1"
        },
        {
            "id": "901",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/39ef/fxmyrzjyn9m94yy6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/cf36/nezx7cojg20aqbc6g.jpg",
            "movieName": "Saak (2019)",
            "htmlFile": "https://www.8952",
            "directOne": "Punjabi",
            "imbd": "6.4",
            "rating": "HD 720p",
            "catergory": "Drama",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "907",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/c8f4/zid4ggeep9heq406g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/07ea/xpjv5gf7csybg4s6g.jpg",
            "movieName": "Ardab Mutiyaran (2019)",
            "htmlFile": "https://www.8878",
            "directOne": "Punjabi",
            "imbd": "7.2",
            "rating": "HD 720p",
            "catergory": "Drama",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "919",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/9c5b/u1jkf38wmgzrulv6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/bd4b/kiv6ep6i30szmc86g.jpg",
            "movieName": "Unni Ikki (2019)",
            "htmlFile": "https://www.8840",
            "directOne": "Punjabi",
            "imbd": "7.6",
            "rating": "HD 720p",
            "catergory": "Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "933",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/675d/bw99lip2y1icuij6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/f120/wrzajysd0zzfosc6g.jpg",
            "movieName": "Tara Mira (2019)",
            "htmlFile": "https://www.8787",
            "directOne": "Punjabi",
            "imbd": "6.6",
            "rating": "pDVDRip",
            "catergory": "Drama",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "944",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/8d8a/todpenyiycm6ogp6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/1706/6hfr3axk8giamw16g.jpg",
            "movieName": "Jaddi Sardar (2019)",
            "htmlFile": "https://www.8712",
            "directOne": "Punjabi",
            "imbd": "6.0",
            "rating": "HD 720p",
            "catergory": "Drama",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "977",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/2cfc/gl3onsn1691fqvd6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/a19d/ot0slyjy5i59c2k6g.jpg",
            "movieName": "Naukar Vahuti Da (2019)",
            "htmlFile": "https://www.8485",
            "directOne": "Punjabi",
            "imbd": "5.4",
            "rating": "HD 720p",
            "catergory": "Drama",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1039",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/3160/ft9gosgs4mwip2h6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/381d/tj3sfmihpvy53am6g.jpg",
            "movieName": "Surkhi Bindi (2019)",
            "htmlFile": "https://www.3075",
            "directOne": "Punjabi",
            "imbd": "7.5",
            "rating": "pDVDRip",
            "catergory": "Romance",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1074",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/9226/e4yio01zir81yl86g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/8a04/fp91xhk1vs6m1cj6g.jpg",
            "movieName": "Mindo Taseeldarni (2019)",
            "htmlFile": "https://www.3122",
            "directOne": "Punjabi",
            "imbd": "6.2",
            "rating": "HD 720p",
            "catergory": "Drama",
            "Industry": "Punjabi",
            "latest": "yes",
            "latestCatergory": "yes",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1079",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/1849/3tn15ehglcagsdd6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/8f0d/8ilore5pb9xmvb56g.jpg",
            "movieName": "Kaake Da Viyah (2019)",
            "htmlFile": "https://www.3129",
            "directOne": "Punjabi",
            "imbd": "5.0",
            "rating": "HD 720p",
            "catergory": "Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1085",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/353f/3uy05mzv81v62u76g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/39aa/fklohouttp591ns6g.jpg",
            "movieName": "Family 420 Once Again (2019)",
            "htmlFile": "https://www.3139",
            "directOne": "Punjabi",
            "imbd": "5.1",
            "rating": "HD 720p",
            "catergory": "Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1089",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/ae5b/jmvac2dwmgwqnoe6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/fe0a/f0g5t6eag8kf1z36g.jpg",
            "movieName": "Jugni Yaaran Di (2019)",
            "htmlFile": "https://www.3148",
            "directOne": "Punjabi",
            "imbd": "5.0",
            "rating": "HD 720p",
            "catergory": "Drama",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1093",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/a938/2vz0tc6bvlh9eo76g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/4ca6/dknsgm24vdkviyg6g.jpg",
            "movieName": "Singham (2019)",
            "htmlFile": "https://www.3152",
            "directOne": "Punjabi",
            "imbd": "5.3",
            "rating": "pDVDRip",
            "catergory": "Action",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "yes",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1108",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/7b9d/zkfo8eopca90vfy6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/5f08/qq7adt78oxi9y5w6g.jpg",
            "movieName": "Gangster vs State (2019)",
            "htmlFile": "https://www.3176",
            "directOne": "Punjabi",
            "imbd": "4.5",
            "rating": "HD 720p",
            "catergory": "Action",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1114",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/76b7/lt4qfxuumpnqzws6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/cc9d/wmb7534d61b850q6g.jpg",
            "movieName": "Carry On Jatta (2012)",
            "htmlFile": "https://www.3184",
            "directOne": "Punjabi",
            "imbd": "8.3",
            "rating": "HD 720p",
            "catergory": "Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "yes",
            "keyName": "Carry On Jatta",
            "pathName": "1"
        },
        {
            "id": "1117",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/114e/x2k0fb148fhrqgf6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/5ff9/a10epieq0wxoyay6g.jpg",
            "movieName": "Saadi Marzi (2019)",
            "htmlFile": "https://www.3189",
            "directOne": "Punjabi",
            "imbd": "5.9",
            "rating": "HD 720p",
            "catergory": "Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1119",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/0ad4/85kr04ezwox2pr36g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/ff1d/80yg6fu0y5ygvvg6g.jpg",
            "movieName": "Lukan Mirchi (2019)",
            "htmlFile": "https://www.3192",
            "directOne": "Punjabi",
            "imbd": "5.0",
            "rating": "HD 720p",
            "catergory": "Romance",
            "Industry": "Punjabi",
            "latest": "yes",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1124",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/e8d4/t4nlqvzpol9fgqb6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/069c/q471582icjf4l6j6g.jpg",
            "movieName": "Chandigarh Amritsar Chandigarh (2019)",
            "htmlFile": "https://www.3197",
            "directOne": "Punjabi",
            "imbd": "7.4",
            "rating": "HD 720p",
            "catergory": "Drama",
            "Industry": "Punjabi",
            "latest": "yes",
            "latestCatergory": "yes",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1144",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/a397/knlae698b3jnip16g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/7142/txn4kvhv1dopltg6g.jpg",
            "movieName": "DSP Dev (2019)",
            "htmlFile": "https://www.3229",
            "directOne": "Punjabi",
            "imbd": "5.8",
            "rating": "pDVDRip",
            "catergory": "Action",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1146",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/1b61/w0o1ltjucg2bsg96g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/d2fb/sf8kt72lqkrqxls6g.jpg",
            "movieName": "Muklawa (2019)",
            "htmlFile": "https://www.3231",
            "directOne": "Punjabi",
            "imbd": "6.0",
            "rating": "HD 720p",
            "catergory": "Drama",
            "Industry": "Punjabi",
            "latest": "yes",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1176",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/7fab/sk6j13vovndirrf6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/a59b/n4pj1h3oi3mr1pg6g.jpg",
            "movieName": "Rabb Da Radio 2 (2019)",
            "htmlFile": "https://www.3277",
            "directOne": "Punjabi",
            "imbd": "7.0",
            "rating": "pDVDRip",
            "catergory": "Drama",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "yes",
            "keyName": "Rabb Da Radio",
            "pathName": "2"
        },
        {
            "id": "1179",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/ae0c/xwfvbi4341t3u0e6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/9b7e/4obtf4azpq47ifk6g.jpg",
            "movieName": "Blackia (2019)",
            "htmlFile": "https://www.3280",
            "directOne": "Punjabi",
            "imbd": "6.5",
            "rating": "pDVDRip",
            "catergory": "Drama",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "yes",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1195",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/cb07/vsx1qdjajc6xsut6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/2abf/8x1xvxe89tb81eh6g.jpg",
            "movieName": "Guddiyan Patole (2019)",
            "htmlFile": "https://www.3298",
            "directOne": "Punjabi",
            "imbd": "7.2",
            "rating": "HD 720p",
            "catergory": "Drama",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1196",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/4cd8/pbpcrs922qewhxn6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/be63/iw2wh7f2xiqr0x76g.jpg",
            "movieName": "Uda Aida (2019)",
            "htmlFile": "https://www.3299",
            "directOne": "Punjabi",
            "imbd": "7.7",
            "rating": "pDVDRip",
            "catergory": "Drama",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1219",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/9d28/a8vsbw5bco4qs8r6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/024b/skpx16jm8fxoicv6g.jpg",
            "movieName": "Dulla Vaily (2019)",
            "htmlFile": "https://www.3341",
            "directOne": "Punjabi",
            "imbd": "4.2",
            "rating": "HD 720p",
            "catergory": "Drama",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1240",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/d2a0/w1qokcvxu2yj0lk6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/6ec4/a3dyyw1eode4y416g.jpg",
            "movieName": "Manje Bistre 2 (2019)",
            "htmlFile": "https://www.3377",
            "directOne": "Punjabi",
            "imbd": "5.6",
            "rating": "HD 720p",
            "catergory": "Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "yes",
            "keyName": "Manje Bistre",
            "pathName": "2"
        },
        {
            "id": "1279",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/f8a4/1jrzaiuglp7v7su6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/24df/3w95yy2ksv2cc5d6g.jpg",
            "movieName": "Great Sardaar (2017)",
            "htmlFile": "https://www.3421",
            "directOne": "Punjabi",
            "imbd": "5.4",
            "rating": "HD 1080p",
            "catergory": "Thriller",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1280",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/8c04/h4y2so4i6qr07tb6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/68b8/bdx152cgkjk3f166g.jpg",
            "movieName": "Jagga Jiunda E (2018)",
            "htmlFile": "https://www.3422",
            "directOne": "Punjabi",
            "imbd": "5.9",
            "rating": "HD 1080p",
            "catergory": "Action",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1281",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/09e1/xqrd0zx0bfc2al86g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/3a1f/u1olo5e78hthhvw6g.jpg",
            "movieName": "Paap Ki Kamai [Thanga Magan] (2015)",
            "htmlFile": "https://www.3423",
            "directOne": "Punjabi",
            "imbd": "6.0",
            "rating": "HD 1080p",
            "catergory": "Action",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1282",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/b6bc/elrp9vnl79slixh6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/fd1f/adb5qfay6qnnm5e6g.jpg",
            "movieName": "Ramta Jogi (2015)",
            "htmlFile": "https://www.3424",
            "directOne": "Punjabi",
            "imbd": "7.1",
            "rating": "HD 1080p",
            "catergory": "Romance",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1283",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/05de/nfuupfm9rysytti6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/0ff3/1istk6hq04k8o1i6g.jpg",
            "movieName": "Ranjha Refugee (2018)",
            "htmlFile": "https://www.3425",
            "directOne": "Punjabi",
            "imbd": "5.0",
            "rating": "HD 1080p",
            "catergory": "Drama",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1284",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/114e/x2k0fb148fhrqgf6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/5ff9/a10epieq0wxoyay6g.jpg",
            "movieName": "Saadi Love Story (2013)",
            "htmlFile": "https://www.3426",
            "directOne": "Punjabi",
            "imbd": "5.6",
            "rating": "HD 1080p",
            "catergory": "Romance",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1296",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/9784/ctzodfis7j89rvb6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/9ab6/dlpydp64p1bcb4v6g.jpg",
            "movieName": "Aate Di Chidi (2018)",
            "htmlFile": "https://www.3446",
            "directOne": "Punjabi",
            "imbd": "5.2",
            "rating": "HD 1080p",
            "catergory": "Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1297",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/550f/2x0fs3t9twadm336g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/c33c/ylqxp42ra4y39to6g.jpg",
            "movieName": "Dhol Ratti (2018)",
            "htmlFile": "https://www.3449",
            "directOne": "Punjabi",
            "imbd": "5.8",
            "rating": "HD 1080p",
            "catergory": "Drama",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1298",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/15f7/oli54srtxaadfte6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/1a03/muk0e5kwi5l4rk06g.jpg",
            "movieName": "Baaz (2014)",
            "htmlFile": "https://www.3450",
            "directOne": "Punjabi",
            "imbd": "7.4",
            "rating": "HD 1080p",
            "catergory": "Thriller",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1299",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/47fa/lytpazu0idtnrov6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/f3b8/m4a85onh1e77rfn6g.jpg",
            "movieName": "Control Bhaji Control (2014)",
            "htmlFile": "https://www.3451",
            "directOne": "Punjabi",
            "imbd": "3.5",
            "rating": "HD 1080p",
            "catergory": "Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1300",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/d425/z9a9rlbui3ixysm6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/7059/2141v5utihlb0v16g.jpg",
            "movieName": "Daddy Cool Munde Fool (2013)",
            "htmlFile": "https://www.3453",
            "directOne": "Punjabi",
            "imbd": "6.2",
            "rating": "HD 1080p",
            "catergory": "Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1301",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/1587/wyvexp1qpjqem5f6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/9866/ux1rbw3unaztg4z6g.jpg",
            "movieName": "Fateh (2014)",
            "htmlFile": "https://www.3454",
            "directOne": "Punjabi",
            "imbd": "7.2",
            "rating": "HD 1080p",
            "catergory": "Motivational",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1302",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/a411/k7s566ecw5q2ijk6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/964b/kfu4vndxuxhei7u6g.jpg",
            "movieName": "Hero Naam Yaad Rakhi (2015)",
            "htmlFile": "https://www.3456",
            "directOne": "Punjabi",
            "imbd": "5.6",
            "rating": "HD 1080p",
            "catergory": "Drama",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1303",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/eb62/3ma0r8w4p2mv3ho6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/9ca3/i4bqvx47nmnvkpb6g.jpg",
            "movieName": "Ishq Brandy (2014)",
            "htmlFile": "https://www.3457",
            "directOne": "Punjabi",
            "imbd": "5.7",
            "rating": "HD 1080p",
            "catergory": "Drama",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1304",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/d380/o2u18shu5w3200b6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/713c/vuwa2dobn1cx21b6g.jpg",
            "movieName": "Jatt Airways (2013)",
            "htmlFile": "https://www.3459",
            "directOne": "Punjabi",
            "imbd": "4.4",
            "rating": "HD 1080p",
            "catergory": "Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1305",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/0383/cple2weav64489o6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/0076/4s2vw2ou64jtl456g.jpg",
            "movieName": "Lucky Di Unlucky Story (2013)",
            "htmlFile": "https://www.3460",
            "directOne": "Punjabi",
            "imbd": "6.8",
            "rating": "HD 1080p",
            "catergory": "Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1306",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/3317/ttc1fg38grflbjq6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/754a/e1vzouf3fdu49oh6g.jpg",
            "movieName": "Oh My Pyo (2014)",
            "htmlFile": "https://www.3461",
            "directOne": "Punjabi",
            "imbd": "5.9",
            "rating": "HD 1080p",
            "catergory": "Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1307",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/f72e/atn739hlrcp8qri6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/e5b1/kgcb6jgikv9s2036g.jpg",
            "movieName": "Proper Patola (2014)",
            "htmlFile": "https://www.3462",
            "directOne": "Punjabi",
            "imbd": "5.7",
            "rating": "HD 1080p",
            "catergory": "Drama",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1308",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/be39/ycy5kv5tx9tq9yc6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/0ed8/xs13pxjmgpnx66v6g.jpg",
            "movieName": "Yaaran Da Katchup (2014)",
            "htmlFile": "https://www.3464",
            "directOne": "Punjabi",
            "imbd": "6.5",
            "rating": "HD 1080p",
            "catergory": "Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1335",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/93ce/tgaq0govm0l7pil6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/1dae/k800i58aip78yct6g.jpg",
            "movieName": "Marriage Place (2019)",
            "htmlFile": "https://www.3500",
            "directOne": "Punjabi",
            "imbd": "6.3",
            "rating": "HD 720p",
            "catergory": "Drama",
            "Industry": "Punjabi",
            "latest": "yes",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1371",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/5838/8drudiqnll0s5l06g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/2c24/laza6fngcwyw3ud6g.jpg",
            "movieName": "Rabb Da Radio (2017)",
            "htmlFile": "https://www.3550",
            "directOne": "Punjabi",
            "imbd": "8.2",
            "rating": "HD 720p",
            "catergory": "Drama",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "Rabb Da Radio",
            "pathName": "1"
        },
        {
            "id": "1375",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/1ac5/07ni1ydp47be6c96g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/ac00/25er3x3vu6b9mh66g.jpg",
            "movieName": "Qismat (2018)",
            "htmlFile": "https://www.3554",
            "directOne": "Punjabi",
            "imbd": "8.5",
            "rating": "pDVDRip",
            "catergory": "Romance,Drama",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1412",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/2a20/4pr1h0359axza366g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/b231/36e0cf40pn4dqm46g.jpg",
            "movieName": "Afsar (2018)",
            "htmlFile": "https://www.3605",
            "directOne": "Punjabi",
            "imbd": "4.5",
            "rating": "HD 720p",
            "catergory": "Drama",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1420",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/2030/zsbdq4v894p3wbx6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/9179/win6rf3dibrqylq6g.jpg",
            "movieName": "Mr & Mrs 420 Returns (2018)",
            "htmlFile": "https://www.3616",
            "directOne": "Punjabi",
            "imbd": "6.6",
            "rating": "HD 720p",
            "catergory": "Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "yes",
            "keyName": "Mr & Mrs 420",
            "pathName": "2"
        },
        {
            "id": "1422",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/e12d/oavkspwerxzdd3m6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/f682/1aqv9pbl3zm6lxs6g.jpg",
            "movieName": "Carry on Jatta 2 (2018)",
            "htmlFile": "https://www.3618",
            "directOne": "Punjabi",
            "imbd": "6.9",
            "rating": "HD 720p",
            "catergory": "Comedy",
            "Industry": "Punjabi",
            "latest": "yes",
            "latestCatergory": "yes",
            "keyName": "Carry On Jatta",
            "pathName": "2"
        },
        {
            "id": "1428",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/ba64/kpxxh6nqs4nsuy76g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/e14c/5rgl62uteoigudf6g.jpg",
            "movieName": "Raduaa (2018)",
            "htmlFile": "https://www.3625",
            "directOne": "Punjabi",
            "imbd": "5.0",
            "rating": "HD 720p",
            "catergory": "Drama",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1429",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/0b55/ckgrw11oncstcbi6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/b119/98m80msda56zsls6g.jpg",
            "movieName": "Aa Gaye Munde U.K. De (2014)",
            "htmlFile": "https://www.3626",
            "directOne": "Punjabi",
            "imbd": "5.7",
            "rating": "HD 720p",
            "catergory": "Romance,Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1434",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/33f8/1yaw1u9ssgujrfk6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/81aa/bjfwhd692m9kmyp6g.jpg",
            "movieName": "Sajjan Singh Rangroot (2018)",
            "htmlFile": "https://www.3635",
            "directOne": "Punjabi",
            "imbd": "7.5",
            "rating": "HD 720p",
            "catergory": "Drama,Motivational",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1455",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/126d/vaujopj7qq7clq06g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/5299/awy88nbolel4s7j6g.jpg",
            "movieName": "Vadhayiyaan Ji Vadhayiyaan (2018)",
            "htmlFile": "https://www.3663",
            "directOne": "Punjabi",
            "imbd": "6.7",
            "rating": "HD 720p",
            "catergory": "Comedy,Romance",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1493",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/5417/mxr6vlivangobh06g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/c4f1/p7oqivcpv3ppnet6g.jpg",
            "movieName": "Daana Paani (2018)",
            "htmlFile": "https://www.3739",
            "directOne": "Punjabi",
            "imbd": "7.9",
            "rating": "HD 720p",
            "catergory": "Drama",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1494",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/e88f/lm2mhqdiux6jpl16g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/6571/edzcnwmi0912lz06g.jpg",
            "movieName": "Golak Bugni Bank Te Batua (2018)",
            "htmlFile": "https://www.3741",
            "directOne": "Punjabi",
            "imbd": "7.1",
            "rating": "HD 720p",
            "catergory": "Drama",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "yes",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1495",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/b0c2/k8yl5mgwkivmku26g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/b9f7/4a7e1y8jan7lz636g.jpg",
            "movieName": "JATT vs IELTS (2018)",
            "htmlFile": "https://www.3742",
            "directOne": "Punjabi",
            "imbd": "5.8",
            "rating": "HD 720p",
            "catergory": "Drama,Romance",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1496",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/58c2/0it9lao4s88qsri6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/d2d5/k06xybdat1kcbi26g.jpg",
            "movieName": "Kurmaiyan (2018)",
            "htmlFile": "https://www.3745",
            "directOne": "Punjabi",
            "imbd": "5.7",
            "rating": "HD 720p",
            "catergory": "Drama,Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1497",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/7dd2/d59unz8yebws4gu6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/f05a/k8eliuh7pyj2m7u6g.jpg",
            "movieName": "Laavaan Phere (2018)",
            "htmlFile": "https://www.3746",
            "directOne": "Punjabi",
            "imbd": "5.3",
            "rating": "HD 720p",
            "catergory": "Drama,Romance",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "yes",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "1498",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/aab3/4y0vsvxffprmon76g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/eb0e/xb6aaiiywpbto5v6g.jpg",
            "movieName": "Laung Laachi (2018)",
            "htmlFile": "https://www.3747",
            "directOne": "Punjabi",
            "imbd": "5.7",
            "rating": "HD 720p",
            "catergory": "Drama,Romance",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "yes",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "2209",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/694d/cbxkp9zcutjcpvf6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/a739/g9pa5guceeu0rc96g.jpg",
            "movieName": "Angrej (2015)",
            "htmlFile": "https://www.4750",
            "directOne": "Punjabi",
            "imbd": "8.6",
            "rating": "HD 720p",
            "catergory": "Comedy,Drama",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "2210",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/5447/az7an8w4hvrbjis6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/d654/veo7mut2s5idubp6g.jpg",
            "movieName": "Ardaas (2016)",
            "htmlFile": "https://www.4751",
            "directOne": "Punjabi",
            "imbd": "8.4",
            "rating": "HD 720p",
            "catergory": "Drama",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "2211",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/1ff6/1pxd5acaz1x9co16g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/1aae/xiqt3m5kp39briy6g.jpg",
            "movieName": "Arjan (2017)",
            "htmlFile": "https://www.4752",
            "directOne": "Punjabi",
            "imbd": "7.2",
            "rating": "HD 720p",
            "catergory": "Drama,Romance",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "2212",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/032d/j3ki5kvmicnhh5u6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/acca/69eqftnuzera9us6g.jpg",
            "movieName": "Bailaras (2017)",
            "htmlFile": "https://www.4753",
            "directOne": "Punjabi",
            "imbd": "6.5",
            "rating": "HD 720p",
            "catergory": "Drama",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "2213",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/785d/dvy7ksvoz5d4rds6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/a2a4/xe0v1htk1ni3ce46g.jpg",
            "movieName": "Best of Luck (2013)",
            "htmlFile": "https://www.4755",
            "directOne": "Punjabi",
            "imbd": "5.6",
            "rating": "HD 720p",
            "catergory": "Action,Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "2214",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/43c8/f8pkbzt1mjredq16g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/2ba1/bcqe2vqfd1xwic76g.jpg",
            "movieName": "Chaar Sahibzaade (2014)",
            "htmlFile": "https://www.4756",
            "directOne": "Punjabi",
            "imbd": "8.0",
            "rating": "HD 720p",
            "catergory": "Animated",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "yes",
            "keyName": "Chaar Sahibzaade",
            "pathName": "1"
        },
        {
            "id": "2215",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/8a76/ksq8uxvbuuj98rp6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/c3c0/qywwsyxatqpki0l6g.jpg",
            "movieName": "Chaar Sahibzaade Rise of Banda Singh Bahadur (2016)",
            "htmlFile": "https://www.4757",
            "directOne": "Punjabi",
            "imbd": "8.6",
            "rating": "HD 720p",
            "catergory": "Animated",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "Chaar Sahibzaade",
            "pathName": "2"
        },
        {
            "id": "2216",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/efb9/aad843mbkn5gsto6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/e2e4/0cw6cc71v0l5vlu6g.jpg",
            "movieName": "Channa Mereya (2017)",
            "htmlFile": "https://www.4758",
            "directOne": "Punjabi",
            "imbd": "6.4",
            "rating": "HD 720p",
            "catergory": "Romance,Drama",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "2217",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/17bc/pjb7d03md3i2bi86g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/1440/52gk4wjniufynzz6g.jpg",
            "movieName": "Dangar Doctor Jelly (2017)",
            "htmlFile": "https://www.4759",
            "directOne": "Punjabi",
            "imbd": "5.5",
            "rating": "HD 720p",
            "catergory": "Drama,Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "yes",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "2218",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/bd08/mmy9cbj9ezwp8186g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/7dab/jepe0nee44tnf656g.jpg",
            "movieName": "Disco Singh (2014)",
            "htmlFile": "https://www.4763",
            "directOne": "Punjabi",
            "imbd": "5.7",
            "rating": "HD 720p",
            "catergory": "Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "yes",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "2219",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/7886/w6sn75mrczu4f9l6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/e749/i7kv2snbi0yrcev6g.jpg",
            "movieName": "Goreyan Nu Daffa Karo (2014)",
            "htmlFile": "https://www.4764",
            "directOne": "Punjabi",
            "imbd": "7.4",
            "rating": "HD 720p",
            "catergory": "Comedy,Romance",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "yes",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "2220",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/9863/qt9syn1zmbl60uu6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/4ed2/1jbtuuwosafi7cg6g.jpg",
            "movieName": "Jatt & Juliet 2 (2013)",
            "htmlFile": "https://www.4765",
            "directOne": "Punjabi",
            "imbd": "7.4",
            "rating": "HD 720p",
            "catergory": "Romance,Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "yes",
            "keyName": "Jatt & Juliet",
            "pathName": "2"
        },
        {
            "id": "2221",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/c76c/oahus34laoyhv2u6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/45ec/5lapqrcpyyi5tju6g.jpg",
            "movieName": "Jindua (2017)",
            "htmlFile": "https://www.4768",
            "directOne": "Punjabi",
            "imbd": "6.6",
            "rating": "HD 720p",
            "catergory": "Drama",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "2222",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/7a8a/2erf4zem3x3ruof6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/789d/2k2yfhnpzulfx3j6g.jpg",
            "movieName": "Jora 10 Numbaria (2017)",
            "htmlFile": "https://www.4769",
            "directOne": "Punjabi",
            "imbd": "6.9",
            "rating": "HD 720p",
            "catergory": "Drama,Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "2223",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/8d11/coto6eokeet8az36g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/69e2/fip5pjd6cnmrsfj6g.jpg",
            "movieName": "Kande (2018)",
            "htmlFile": "https://www.4771",
            "directOne": "Punjabi",
            "imbd": "6.4",
            "rating": "HD 720p",
            "catergory": "Drama,Action",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "2224",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/07ad/vv3rpdfej2s6mce6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/5da3/lgdkq5dccoc9sun6g.jpg",
            "movieName": "Kirdar e Sardar (2017)",
            "htmlFile": "https://www.4773",
            "directOne": "Punjabi",
            "imbd": "7.4",
            "rating": "HD 720p",
            "catergory": "Drama,Action",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "yes",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "2225",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/ff78/8bklpbbadiq9p0g6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/38f2/0loqs3elm5x7nz76g.jpg",
            "movieName": "Krazzy Tabbar (2017)",
            "htmlFile": "https://www.4774",
            "directOne": "Punjabi",
            "imbd": "5.5",
            "rating": "HD 720p",
            "catergory": "Drama,Romance",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "yes",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "2226",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/7866/c87u78i7b4be2x86g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/cdd6/fmt2oxhmdfdzblu6g.jpg",
            "movieName": "Love Punjab (2016)",
            "htmlFile": "https://www.4777",
            "directOne": "Punjabi",
            "imbd": "7.6",
            "rating": "HD 720p",
            "catergory": "Drama,Romance",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "2227",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/6d5d/80bc48pmp4e20536g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/24c2/9l73rvp763bnmla6g.jpg",
            "movieName": "Mahi NRI (2017)",
            "htmlFile": "https://www.4778",
            "directOne": "Punjabi",
            "imbd": "6.3",
            "rating": "HD 720p",
            "catergory": "Drama,Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "yes",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "2228",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/195b/cuzzwvdvoiopz0n6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/239c/3lndxebpq36ic6a6g.jpg",
            "movieName": "Mr & Mrs 420 (2014)",
            "htmlFile": "https://www.4781",
            "directOne": "Punjabi",
            "imbd": "7.2",
            "rating": "HD 720p",
            "catergory": "Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "yes",
            "keyName": "Mr & Mrs 420",
            "pathName": "1"
        },
        {
            "id": "2229",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/37ae/9ctp0g2lqec1zwy6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/19e6/6h7jxv71fdciv656g.jpg",
            "movieName": "Munde Kamaal De (2015)",
            "htmlFile": "https://www.4783",
            "directOne": "Punjabi",
            "imbd": "6.4",
            "rating": "HD 720p",
            "catergory": "Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "yes",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "2230",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/87da/a48rblsx0cvwi9b6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/a442/ayaq5livwg9z04r6g.jpg",
            "movieName": "Nikka Zaildar (2016)",
            "htmlFile": "https://www.4785",
            "directOne": "Punjabi",
            "imbd": "7.5",
            "rating": "HD 720p",
            "catergory": "Drama",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "yes",
            "keyName": "Nikka Zaildar",
            "pathName": "1"
        },
        {
            "id": "2231",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/86aa/wrs283oawnvbzw76g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/9df0/3z7po5xmm0dgd6l6g.jpg",
            "movieName": "Nikka Zaildar 2 (2017)",
            "htmlFile": "https://www.4786",
            "directOne": "Punjabi",
            "imbd": "6.7",
            "rating": "HD 720p",
            "catergory": "Drama",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "Nikka Zaildar",
            "pathName": "2"
        },
        {
            "id": "2232",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/cffa/302v5mgb4tefb2b6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/8005/urmhsume690oxrj6g.jpg",
            "movieName": "Once Upon A Time in Amritsar (2016)",
            "htmlFile": "https://www.4787",
            "directOne": "Punjabi",
            "imbd": "5.8",
            "rating": "HD 720p",
            "catergory": "Drama",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "2233",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/03f4/h9xzdv95pguhyxi6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/0959/44fg3h0k8rmlbym6g.jpg",
            "movieName": "Rocky Mental (2017)",
            "htmlFile": "https://www.4792",
            "directOne": "Punjabi",
            "imbd": "5.6",
            "rating": "HD 720p",
            "catergory": "Drama,Action",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "yes",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "2234",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/255a/hqgwsyc17iq5dyi6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/a09d/3nb1cf19lhtfzlt6g.jpg",
            "movieName": "Rupinder Gandhi 1 (2016)",
            "htmlFile": "https://www.4793",
            "directOne": "Punjabi",
            "imbd": "7.5",
            "rating": "HD 720p",
            "catergory": "Drama,Action",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "yes",
            "keyName": "Rupinder Gandhi",
            "pathName": "1"
        },
        {
            "id": "2235",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/446f/vx0ina1lijaxb166g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/fc6c/46axaaao5ioyf1q6g.jpg",
            "movieName": "Rupinder Gandhi 2 The Robinhood (2017)",
            "htmlFile": "https://www.4794",
            "directOne": "Punjabi",
            "imbd": "7.6",
            "rating": "HD 720p",
            "catergory": "Drama,Action",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "Rupinder Gandhi",
            "pathName": "2"
        },
        {
            "id": "2236",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/5234/e709ajce6cujiti6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/d43b/s8jy1nprwn9h7rt6g.jpg",
            "movieName": "Sardar Mohammad (2017)",
            "htmlFile": "https://www.4797",
            "directOne": "Punjabi",
            "imbd": "7.5",
            "rating": "HD 720p",
            "catergory": "Drama,Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "2237",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/88fb/e4hpf2abf1pcxvz6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/b8f6/sj1m7ua5rj8sjjl6g.jpg",
            "movieName": "Singh vs Kaur (2013)",
            "htmlFile": "https://www.4800",
            "directOne": "Punjabi",
            "imbd": "6.7",
            "rating": "HD 720p",
            "catergory": "Romance,Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "yes",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "2238",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/c4d2/9ycdi9il8bahezf6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/eb99/86r1p8kkknk94516g.jpg",
            "movieName": "Toofan Singh (2017)",
            "htmlFile": "https://www.4806",
            "directOne": "Punjabi",
            "imbd": "6.9",
            "rating": "HD 720p",
            "catergory": "Drama,Action",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "2239",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/0381/5ot9s92plnnxqz36g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/9ead/8hoi1v6vm1e85lf6g.jpg",
            "movieName": "Tu Mera 22 Main Tera 22 (2013)",
            "htmlFile": "https://www.4807",
            "directOne": "Punjabi",
            "imbd": "5.5",
            "rating": "HD 720p",
            "catergory": "Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "2240",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/f5b3/o5tiq2kezkaomt76g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/5dd0/6118am7h1zk7wrl6g.jpg",
            "movieName": "Vaapsi (2016)",
            "htmlFile": "https://www.4808",
            "directOne": "Punjabi",
            "imbd": "7.6",
            "rating": "HD 720p",
            "catergory": "Drama,Sport",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "2241",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/c418/w64nva6rgy5zar46g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/d989/tr9ln3iu32mtxsq6g.jpg",
            "movieName": "Vaiskhi List (2016)",
            "htmlFile": "https://www.4809",
            "directOne": "Punjabi",
            "imbd": "6.4",
            "rating": "HD 720p",
            "catergory": "Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "yes",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "2242",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/1754/jorpm6smzzoxbog6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/223e/w5zdfne5kj6bhgw6g.jpg",
            "movieName": "Viyah 70 KM (2013)",
            "htmlFile": "https://www.4810",
            "directOne": "Punjabi",
            "imbd": "5.8",
            "rating": "HD 720p",
            "catergory": "Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "2243",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/eb14/czdhxdhhdobljha6g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/d2b3/1k9ljoggqy82no56g.jpg",
            "movieName": "Yaar Anmulle (2011)",
            "htmlFile": "https://www.4811",
            "directOne": "Punjabi",
            "imbd": "7.5",
            "rating": "HD 720p",
            "catergory": "Comedy",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "yes",
            "keyName": "FALSE",
            "pathName": "FALSE"
        },
        {
            "id": "2244",
            "ImageUrlHorizontal": "https://www.mediafire.com/convkey/dcd1/jtb2c265mkkad606g.jpg",
            "ImageUrlVertical": "https://www.mediafire.com/convkey/33c9/45kas9n8guyba0i6g.jpg",
            "movieName": "Zubaan (2016)",
            "htmlFile": "https://www.4812",
            "directOne": "Punjabi",
            "imbd": "6.2",
            "rating": "HD 720p",
            "catergory": "Drama",
            "Industry": "Punjabi",
            "latest": "no",
            "latestCatergory": "FALSE",
            "keyName": "FALSE",
            "pathName": "FALSE"
        }
    ]
}
